export const metadata = {
  title: 'Terms of Service — VivAI',
};

export default function TermsOfServicePage() {
  return (
    <div className="tos-wrap">
      <div className="tos-card">
        <h1>Terms of Service</h1>
        <p className="tos-updated">Last updated: {new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}</p>

        <p>
          These Terms of Service (&quot;Terms&quot;) govern your access to and use of VivAI
          (the &quot;Service&quot;). By creating an account, checking the agreement box at
          signup, or otherwise using the Service, you agree to be bound by these Terms. If
          you do not agree, do not create an account or use the Service.
        </p>

        <h2>1. The Service</h2>
        <p>
          The Service provides access to an AI chat interface. Responses are generated by an
          automated language model. Outputs may be inaccurate, incomplete, offensive, or
          otherwise objectionable. The Service is provided for informational and personal use
          only and is not a substitute for professional advice of any kind.
        </p>

        <h2>2. Your Responsibilities</h2>
        <p>
          You are solely responsible for your account, everything you input into the Service,
          and everything you do with any output you receive from it. You agree not to use the
          Service for any unlawful purpose, to generate or distribute content that infringes
          on the rights of others, or to attempt to disrupt, reverse-engineer, or abuse the
          Service. You agree to comply with all applicable local, state, national, and
          international laws in connection with your use of the Service.
        </p>

        <h2>3. No Warranty</h2>
        <p>
          THE SERVICE AND ALL OUTPUT ARE PROVIDED &quot;AS IS&quot; AND &quot;AS
          AVAILABLE,&quot; WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING
          WITHOUT LIMITATION WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR
          PURPOSE, NON-INFRINGEMENT, ACCURACY, OR RELIABILITY. WE DO NOT WARRANT THAT THE
          SERVICE WILL BE UNINTERRUPTED, ERROR-FREE, OR SECURE.
        </p>

        <h2>4. Limitation of Liability</h2>
        <p>
          TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, IN NO EVENT WILL THE OPERATOR OF
          VIVAI, ITS AFFILIATES, OR ANY OF THEIR RESPECTIVE OFFICERS, DIRECTORS, EMPLOYEES,
          OR AGENTS BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, EXEMPLARY,
          OR PUNITIVE DAMAGES, OR ANY LOSS OF PROFITS, DATA, GOODWILL, OR OTHER INTANGIBLE
          LOSSES, ARISING OUT OF OR RELATED TO YOUR USE OF, OR INABILITY TO USE, THE SERVICE
          — REGARDLESS OF THE LEGAL THEORY ON WHICH THE CLAIM IS BASED, AND EVEN IF ADVISED OF
          THE POSSIBILITY OF SUCH DAMAGES. THE OPERATOR&apos;S TOTAL AGGREGATE LIABILITY FOR
          ANY CLAIM ARISING FROM OR RELATED TO THE SERVICE WILL NOT EXCEED THE GREATER OF (A)
          THE AMOUNT YOU PAID TO USE THE SERVICE IN THE 12 MONTHS PRECEDING THE CLAIM, OR (B)
          TEN U.S. DOLLARS ($10).
        </p>

        <h2>5. Indemnification</h2>
        <p>
          You agree to defend, indemnify, and hold harmless the operator of VivAI and its
          affiliates from and against any claims, damages, losses, liabilities, costs, and
          expenses (including reasonable attorneys&apos; fees) arising out of or related to
          your use of the Service, your violation of these Terms, or your violation of any
          rights of another person or entity.
        </p>

        <h2>6. User Conduct &amp; Termination</h2>
        <p>
          We may suspend or terminate your access to the Service at any time, for any reason
          or no reason, without notice or liability. Nothing in these Terms obligates us to
          monitor, review, or moderate any input or output, though we may do so at our
          discretion.
        </p>

        <h2>7. Changes</h2>
        <p>
          We may update these Terms at any time. Continued use of the Service after changes
          are posted constitutes your acceptance of the revised Terms.
        </p>

        <h2 id="no-liability">8. Disclaimer of Liability — In Plain Terms</h2>
        <p className="tos-callout">
          To be completely explicit, separate from and in addition to the sections above: the
          operator of VivAI is <strong>not liable, under any circumstances, for anything a
          user does using this Service</strong> — including, without limitation, anything
          illegal, harmful, offensive, fraudulent, infringing, or otherwise inappropriate that
          a user inputs, generates, or does with any output. Users act entirely on their own
          behalf and at their own risk, and are solely and fully responsible for their own
          conduct and its consequences. By using the Service, you agree that the operator
          bears no responsibility or liability whatsoever for how you or any other user uses
          it.
        </p>

        <h2>9. Contact</h2>
        <p>
          Questions about these Terms can be directed to the operator of the Service through
          the contact channel provided within the app, where available.
        </p>
      </div>
    </div>
  );
}
